FROM scratch

ADD 1f3b07bb230982ccbef152abf8a8a95523cb909141008196e0c802df2b11e212.tar.xz /
ADD 492ed3e0a388ee2165fb124d16dc753405d7bc9c2b8c0895b9d4df8ae6bdd354.tar.xz /
ADD c914f08cd9bffb606b199952fa0fb3a3a049c9a14c4c392ddba9d9f9cca1147d.tar.xz /
ADD cdc48ef48f27fa925ab117509f8183cd374488dde4c2a7b3c4b8cb2af97d6b0e.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]
