FROM scratch

ADD 568e677d96f086b1d36b3f45e9c913ce0c39d65f26978caa72c11551ff3ed691.tar.xz /
ADD 6285bae9f9cab192b7ebe3255b4ab10803ea7a804c28cb9c22635896a80af521.tar.xz /
ADD 94d812b4b4f7914b0e4d16ac9cc85e71daeeee6e3b8d5a25c3be935d9d67ce85.tar.xz /
ADD f9a3fa618aaa0fb109484074fb1172dd944c5e8851be75a5fc144af94e95d4db.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]
